# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconocimientosMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100)),
                ('reconocimiento', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('fuente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Reconocimientos Docente',
                'verbose_name': 'Reconocimiento Docente',
            },
        ),
        migrations.CreateModel(
            name='RegimenDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regimen', models.CharField(choices=[('DX', 'Dedicacion Exclusiva'), ('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial'), ('PA', 'Pasantia'), ('PC', 'Practicante')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Regimen Docentes',
                'verbose_name': 'Regimen Docente',
            },
        ),
    ]
