# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconocimientosmdl',
            name='fecha',
            field=models.DateField(),
        ),
    ]
