# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catedra', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('tipo_categoria', models.CharField(choices=[('AX', 'Auxiliar'), ('P', 'Principal'), ('AS', 'Asociado')], max_length=2)),
                ('date_inicio', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria Docente',
                'verbose_name_plural': 'Categoria Docentes',
            },
        ),
    ]
