# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigacionModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('isbn', models.IntegerField()),
                ('medio_publicacion', models.CharField(max_length=100)),
                ('num_paginas', models.IntegerField()),
                ('tipo_publicacion', models.CharField(max_length=100)),
                ('titulo_publicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Investigaciones',
                'verbose_name': 'Investigación',
            },
        ),
    ]
