# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regimen', models.CharField(choices=[('DX', 'Dedicacion Exclusiva'), ('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial'), ('PA', 'Pasantia'), ('PC', 'Practicante')], max_length=2)),
            ],
            options={
                'verbose_name': 'Regimen Docente',
                'verbose_name_plural': 'Regimen Docentes',
            },
        ),
    ]
